item {
    id: 1
    display_name: "glasses"
}

item {
    id: 2
    display_name: "gloves"
}

item {
    id: 3
    display_name: "helmet"
}

item {
    id: 4
    display_name: "mask"
}

item {
    id: 5
    display_name: "suit"
}

